name: get-resolvers

# inspired from https://github.com/BonJarber/fresh-resolvers/blob/main/.github/workflows/refresh-resolvers.yaml
# which seems to be broken now
on:
  push

jobs:
  get-resolvers:
    runs-on: ubuntu-20.04
    steps:

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
    
      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'vortexau/dnsvalidator'
          path: dnsvalidator
    
      - name: Install and run DNS Validator
        run: |
          cd dnsvalidator
          python3 setup.py install
          pip install contextvars
          dnsvalidator -tL https://gist.githubusercontent.com/devanshbatham/ae9a4ccfb9e00ca4e1cc71f8a5d53768/raw/49d82a511b27f7ebf7fac5e9d789067e8a559bbd/nameservers.txt -threads 80 --silent -o resolvers.txt
    
      
      - name: Commit
        run: |
          git config --local user.email "research@sybilscan.com"
          git config --local user.name "[bot] sybsilscan"
          git add resolvers.txt
          git commit -m "✨ Updating Resolvers"
    
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main